# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kv_cache_pb2 as kv__cache__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kv_cache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVCacheServiceStub(object):
    """─────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Store = channel.unary_unary(
                '/kvcache.KVCacheService/Store',
                request_serializer=kv__cache__pb2.StoreRequest.SerializeToString,
                response_deserializer=kv__cache__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.Fetch = channel.unary_unary(
                '/kvcache.KVCacheService/Fetch',
                request_serializer=kv__cache__pb2.FetchRequest.SerializeToString,
                response_deserializer=kv__cache__pb2.FetchResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kvcache.KVCacheService/Delete',
                request_serializer=kv__cache__pb2.DeleteRequest.SerializeToString,
                response_deserializer=kv__cache__pb2.DeleteResponse.FromString,
                _registered_method=True)


class KVCacheServiceServicer(object):
    """─────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────
    """

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVCacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Store': grpc.unary_unary_rpc_method_handler(
                    servicer.Store,
                    request_deserializer=kv__cache__pb2.StoreRequest.FromString,
                    response_serializer=kv__cache__pb2.StoreResponse.SerializeToString,
            ),
            'Fetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=kv__cache__pb2.FetchRequest.FromString,
                    response_serializer=kv__cache__pb2.FetchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kv__cache__pb2.DeleteRequest.FromString,
                    response_serializer=kv__cache__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvcache.KVCacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvcache.KVCacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVCacheService(object):
    """─────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────
    """

    @staticmethod
    def Store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KVCacheService/Store',
            kv__cache__pb2.StoreRequest.SerializeToString,
            kv__cache__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KVCacheService/Fetch',
            kv__cache__pb2.FetchRequest.SerializeToString,
            kv__cache__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KVCacheService/Delete',
            kv__cache__pb2.DeleteRequest.SerializeToString,
            kv__cache__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
