# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv_cache.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kv_cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv_cache.proto\x12\x07kvcache\"[\n\nKVCacheKey\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\nworld_size\x18\x02 \x01(\x05\x12\x11\n\tworker_id\x18\x03 \x01(\x05\x12\x12\n\nchunk_hash\x18\x04 \x01(\x03\"N\n\x08KVTensor\x12%\n\tprecision\x18\x01 \x01(\x0e\x32\x12.kvcache.Precision\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\"k\n\x07LayerKV\x12\x10\n\x08layer_id\x18\x01 \x01(\x05\x12%\n\nkey_tensor\x18\x02 \x01(\x0b\x32\x11.kvcache.KVTensor\x12\'\n\x0cvalue_tensor\x18\x03 \x01(\x0b\x32\x11.kvcache.KVTensor\"D\n\x0cKVCacheValue\x12 \n\x06layers\x18\x01 \x03(\x0b\x32\x10.kvcache.LayerKV\x12\x12\n\nnum_tokens\x18\x02 \x01(\x05\"V\n\x0cStoreRequest\x12 \n\x03key\x18\x01 \x01(\x0b\x32\x13.kvcache.KVCacheKey\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.kvcache.KVCacheValue\"1\n\rStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0c\x46\x65tchRequest\x12 \n\x03key\x18\x01 \x01(\x0b\x32\x13.kvcache.KVCacheKey\"\\\n\rFetchResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.kvcache.KVCacheValue\x12\x16\n\x0ematched_tokens\x18\x03 \x01(\x05\"1\n\rDeleteRequest\x12 \n\x03key\x18\x01 \x01(\x0b\x32\x13.kvcache.KVCacheKey\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*^\n\tPrecision\x12\x15\n\x11PRECISION_UNKNOWN\x10\x00\x12\x12\n\x0ePRECISION_FP16\x10\x01\x12\x12\n\x0ePRECISION_BF16\x10\x02\x12\x12\n\x0ePRECISION_FP32\x10\x03\x32\xbb\x01\n\x0eKVCacheService\x12\x36\n\x05Store\x12\x15.kvcache.StoreRequest\x1a\x16.kvcache.StoreResponse\x12\x36\n\x05\x46\x65tch\x12\x15.kvcache.FetchRequest\x1a\x16.kvcache.FetchResponse\x12\x39\n\x06\x44\x65lete\x12\x16.kvcache.DeleteRequest\x1a\x17.kvcache.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRECISION']._serialized_start=765
  _globals['_PRECISION']._serialized_end=859
  _globals['_KVCACHEKEY']._serialized_start=27
  _globals['_KVCACHEKEY']._serialized_end=118
  _globals['_KVTENSOR']._serialized_start=120
  _globals['_KVTENSOR']._serialized_end=198
  _globals['_LAYERKV']._serialized_start=200
  _globals['_LAYERKV']._serialized_end=307
  _globals['_KVCACHEVALUE']._serialized_start=309
  _globals['_KVCACHEVALUE']._serialized_end=377
  _globals['_STOREREQUEST']._serialized_start=379
  _globals['_STOREREQUEST']._serialized_end=465
  _globals['_STORERESPONSE']._serialized_start=467
  _globals['_STORERESPONSE']._serialized_end=516
  _globals['_FETCHREQUEST']._serialized_start=518
  _globals['_FETCHREQUEST']._serialized_end=566
  _globals['_FETCHRESPONSE']._serialized_start=568
  _globals['_FETCHRESPONSE']._serialized_end=660
  _globals['_DELETEREQUEST']._serialized_start=662
  _globals['_DELETEREQUEST']._serialized_end=711
  _globals['_DELETERESPONSE']._serialized_start=713
  _globals['_DELETERESPONSE']._serialized_end=763
  _globals['_KVCACHESERVICE']._serialized_start=862
  _globals['_KVCACHESERVICE']._serialized_end=1049
# @@protoc_insertion_point(module_scope)
